name: Publish

on:
  push:
    tags: [ v* ]

env:
  REGISTRY_REPO: alpoi/typst-packages
  PACKAGE_NAME: kiresume
  PATH_PREFIX: packages/preview

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build package
        run: |
          mkdir -p out
          cp -r examples \
            src \
            template \
            LICENSE \
            README.md \
            typst.toml \
            out

      - name: Checkout package registry
        uses: actions/checkout@v4
        with:
          repository: ${{ env.REGISTRY_REPO }}
          token: ${{ secrets.REGISTRY_TOKEN }}
          path: typst-packages

      - name: Publish package
        run: |
          PKG_VERSION="${{ github.ref_name }}"
          PKG_VERSION=${PKG_VERSION:1}
          mkdir -p typst-packages/${{ env.PATH_PREFIX }}/${{ env.PACKAGE_NAME }}/${PKG_VERSION}
          mv "out/*" typst-packages/${{ env.PATH_PREFIX }}/${{ env.PACKAGE_NAME }}/${PKG_VERSION}
          rm -rf out

          cd typst-packages
          git config user.name "alpoi [bot]"
          git config user.email "me@angus.buzz"
          git checkout -b "${{ env.PACKAGE_NAME }}-${PKG_VERSION}"
          git add .
          git commit -m "${{ env.PACKAGE_NAME }}:${PKG_VERSION}"
          git push --set-upstream origin "${{ env.PACKAGE_NAME }}-${PKG_VERSION}"
